# Templates for Universal Component Generation
#
# This file contains the blueprints for:
# 1. The Manifest (component.yaml)
# 2. The Contract (Pydantic Models)
# 3. The Backend (Python Plugin)
# 4. The Frontend Types (TypeScript Interfaces)

# -----------------------------------------------------------------------------
# 1. Manifest Template
# -----------------------------------------------------------------------------
MANIFEST_TEMPLATE = """schema_version: 1
name: "{name}"
version: "1.0.0"
type: "backend_frontend_hybrid"
description: "{description}"

contract:
  domain: "{domain}"
  methods:
{methods_yaml}

dependencies:
  python:
{python_deps_yaml}
  npm:
{npm_deps_yaml}
  system:
{system_deps_yaml}

ui:
  archetype: "dashboard_widget"
  component_path: "components/{class_name}/Main.tsx"
"""

# -----------------------------------------------------------------------------
# 2. Contract Template (Python/Pydantic)
# -----------------------------------------------------------------------------
CONTRACT_TEMPLATE = """# Contract for Domain: {domain}
# Generated by Piovis Universal Framework

from pydantic import BaseModel
from typing import List, Dict, Optional, Any
from abc import ABC, abstractmethod

# -----------------------------------------------------------------------------
# Data Models (Nouns)
# -----------------------------------------------------------------------------
{data_models}

# -----------------------------------------------------------------------------
# Abstract Base Class (Verbs)
# -----------------------------------------------------------------------------
class {class_name}Contract(ABC):
    
    @abstractmethod
    async def initialize(self, config: Dict[str, Any]) -> bool:
        pass

{abstract_methods}
"""

# -----------------------------------------------------------------------------
# 3. Plugin Implementation Template (Python)
# -----------------------------------------------------------------------------
PLUGIN_TEMPLATE = """# Plugin Implementation: {name}
# Domain: {domain}

import logging
import asyncio
from typing import Dict, Any
from contracts.{domain} import {contract_class}, {import_models}

# Third-party imports
{imports}

logger = logging.getLogger(__name__)

class {class_name}Plugin({contract_class}):
    def __init__(self):
        self._config = {{}}
        self._initialized = False

    async def initialize(self, config: Dict[str, Any]) -> bool:
        self._config = config
        self._initialized = True
        logger.info("{name} initialized")
        return True

{method_implementations}

# Factory function for Discovery
def get_plugin():
    return {class_name}Plugin()
"""

# -----------------------------------------------------------------------------
# 4. TypeScript Interface Template
# -----------------------------------------------------------------------------
TS_INTERFACE_TEMPLATE = """/**
 * TypeScript Interfaces for Domain: {domain}
 * Auto-generated by Piovis Universal Framework
 */

{interfaces}

// Method Signatures for Dispatcher
export interface {class_name}API {{
{method_signatures}
}}
"""

# -----------------------------------------------------------------------------
# Type Mapping (Python -> TypeScript)
# -----------------------------------------------------------------------------
TYPE_MAP = {
    "str": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
    "dict": "Record<string, any>",
    "list": "any[]",
    "List": "any[]",
    "Any": "any",
    "None": "void",
}
